# Generated by Django 5.0.6 on 2024-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255, null=True)),
                ('Product_price', models.IntegerField(null=True)),
                ('Product_qty', models.IntegerField(null=True)),
                ('Product_img', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
