# Generated by Django 5.0.6 on 2024-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_img',
            new_name='image',
        ),
    ]
